import os
import sys
from alembic.config import Config
from alembic import command
from sqlalchemy import create_engine

def main():
    # Resolve the Backend directory (where this script lives)
    backend_dir = os.path.dirname(os.path.abspath(__file__))

    # Change the working directory to Backend so that Alembic's relative
    # `script_location = alembic` in alembic.ini resolves correctly,
    # regardless of where this script is executed from.
    os.chdir(backend_dir)

    # Ensure Backend is on sys.path so app modules can be imported
    if backend_dir not in sys.path:
        sys.path.insert(0, backend_dir)

    from app.config import settings

    print(f"Loaded DATABASE_URL: {settings.DATABASE_URL}")

    # Test database connection
    print("Testing connection to database...")
    try:
        engine_kwargs = {}
        if settings.DATABASE_URL.startswith("sqlite"):
            engine_kwargs["connect_args"] = {"check_same_thread": False}
        engine = create_engine(settings.DATABASE_URL, **engine_kwargs)
        conn = engine.connect()
        print("✅ Database connection established successfully!")
        conn.close()
    except Exception as e:
        print(f"❌ Database connection failed: {e}")
        print("\nPlease ensure your DATABASE_URL in .env is correct and the target database exists on your PostgreSQL server.")
        sys.exit(1)

    # Initialize Alembic Config
    config_path = os.path.join(backend_dir, "alembic.ini")
    config = Config(config_path)

    # Check if we already have migration scripts in alembic/versions
    versions_dir = os.path.join(backend_dir, "alembic", "versions")
    migration_scripts = [f for f in os.listdir(versions_dir) if f.endswith(".py") and not f.startswith("__")]

    if not migration_scripts:
        print("Generating initial autogenerated migration script...")
        try:
            command.revision(config, message="Initial migration", autogenerate=True)
            print("✅ Initial migration script generated successfully.")
        except Exception as e:
            print(f"❌ Error generating migration script: {e}")
            sys.exit(1)
    else:
        print(f"Found existing migration script(s): {migration_scripts}")

    print("Running database migrations (upgrade head)...")
    try:
        command.upgrade(config, "head")
        print("✅ Database migrations applied successfully!")
    except Exception as e:
        print(f"❌ Error applying migrations: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
